### PR TITLE
fix: resolve flaky TestRoutingKey caused by stale schema metadata cache

### LINKED ISSUE #690: TestRoutingKey is flaky
It fails on driver matrix from time to time
`cassandra_test.go:2321: failed to get routing key info due to error: no metadata available
09:01:38  --- FAIL: TestRoutingKey (1.23s)`

https://jenkins.scylladb.com/job/scylla-2025.4/job/driver-tests/job/gocql-driver-matrix-test/13/

### PR DESCRIPTION
**Pull request by mykaul**
## Summary

Fixes #690 — `TestRoutingKey` integration test flaking with `ErrNoMetadata` / EOF errors.

## Root Cause

`routingKeyInfo()` in `session.go` and `scyllaIsCdcTable()` in `scylla_cdc.go` used `GetKeyspace()` followed by a manual `Tables[name]` map lookup. This pattern **bypasses the cache invalidation logic** that exists in `GetTable()` / `TableMetadata()`.

After a DDL `CREATE TABLE`, the `SCHEMA_CHANGE` event from the cluster is debounced for 1 second (`eventDebounceTime` in `events.go`). If `routingKeyInfo()` executes before the debounce fires, the stale cached `KeyspaceMetadata` doesn't contain the new table, resulting in `ErrNoMetadata`.

### Why it's flaky (not always failing)

With **protocol v4+**, the `PREPARE` response includes `pkeyColumns` directly, so `routingKeyInfo()` takes an early return at `session.go:827-844` and never hits the metadata lookup. The bug only manifests through **protocol v3** code paths where `pkeyColumns` is empty, which happens intermittently depending on timing.

### The architectural gap

Two metadata access patterns exist in the codebase:
- `GetKeyspace()` + `Tables[name]` — does **NOT** handle invalidation (used by the buggy code)
- `GetTable()` / `TableMetadata()` — **does** handle invalidation via `tablesInvalidated` check and `deduplicatedRefreshTable`

### 1. Use `TableMetadata()` in `routingKeyInfo()` and `scyllaIsCdcTable()` (`session.go`, `scylla_cdc.go`)

Replaced the `GetKeyspace()` + `Tables[table]` pattern with `s.TableMetadata(keyspace, table)` which properly handles cache invalidation by checking if the table schema has been invalidated and refreshing from the cluster if needed.

### 2. Invalidate schema cache in `createTable()` test helper (`common_test.go`)

Added `invalidateKeyspaceSchema()` call after DDL execution and schema agreement in the `createTable()` test helper, plus an `extractKeyspaceFromDDL()` parser that handles both `IF NOT EXISTS` and `IF EXISTS` clauses. This ensures the metadata cache is invalidated immediately after table creation, eliminating the race window from the 1-second event debounce.

### 3. Use unique table names in `TestRoutingKey` (`cassandra_test.go`)

Changed `TestRoutingKey` to generate unique table names with a `time.Now().UnixNano()` suffix, enabling the test to run safely with `-count=N` (multiple iterations in the same process) and in parallel.

### Unit tests (`session_unit_test.go`)
Added unit tests using the existing mock infrastructure:
- `TestExtractKeyspaceFromDDL` — validates the DDL keyspace parser (including `IF EXISTS` / `IF NOT EXISTS` handling)
- `TestTableMetadataAfterInvalidation` — verifies `routingKeyInfo()` returns correct metadata after table invalidation
- `TestTableMetadataAfterKeyspaceInvalidation` — same but with keyspace-level invalidation
- `TestScyllaIsCdcTableAfterInvalidation` — verifies `scyllaIsCdcTable()` works correctly after invalidation
- `TestScyllaIsCdcTableNotCdcSuffix` — verifies non-CDC tables are not misidentified

### Integration tests (3-node Scylla 2026.1.0 cluster via ccm)
- `TestRoutingKey` ran **100 times (10 batches of 10 with `-count=10`) — 100/100 passed**
- Full integration test suite (`make test-integration-scylla`) — **all 120+ tests passed**, 0 failures

## Commits

| Commit | Description |
|--------|-------------|
| `671997c` | fix: use `TableMetadata` in `routingKeyInfo` and `scyllaIsCdcTable` |
| `111ef7d` | fix: invalidate schema cache in `createTable` test helper after DDL (with unit tests) |
| `c39914b` | test: use unique table names in `TestRoutingKey` for `-count=N` and parallel safety |

### CODE REVIEW

File: session.go [hunk 1]
```diff
@@ -845,26 +845,18 @@ func (s *Session) routingKeyInfo(ctx context.Context, stmt string, requestTimeou
...
 
 	// get the table metadata
+	// Use TableMetadata (which routes through GetTable) instead of
+	// GetKeyspace + Tables[name] to properly handle cache invalidation
+	// when a table was recently created or altered.
 
-	var keyspaceMetadata *KeyspaceMetadata
-	keyspaceMetadata, inflight.err = s.KeyspaceMetadata(info.request.columns[0].Keyspace)
+	var tableMetadata *TableMetadata
+	tableMetadata, inflight.err = s.TableMetadata(keyspace, table)
```
Comment (sylwiaszunejko) [inline session.go:857]: why change `info.request.columns[0].Keyspace` to `keyspace`?

Comment (mykaul) [reply session.go:857]: Line 818 above already has `keyspace := info.request.keyspace` - is it wrong to re-use it?

Comment (sylwiaszunejko) [reply session.go:857]: I am not sure to be honest, I wonder why it wasn't used before

Comment (dkropachev) [reply session.go:857]: it wasn't present before

Comment (sylwiaszunejko) [reply session.go:857]: `keyspace` variable was present (as @mykaul mentioned in line 818), but for getting keyspace metadata `info.request.columns[0].Keyspace` was used instead of `keyspace` (`info.request.keyspace`)

Comment (mykaul) [reply session.go:857]: I'll fix that. See also the description @ https://github.com/scylladb/gocql/pull/793#discussion_r3015500246

File: cassandra_test.go [hunk 2]
```diff
@@ -2661,16 +2661,21 @@ func TestRoutingKey(t *testing.T) {
 	session := createSession(t)
 	defer session.Close()
 
-	if err := createTable(session, "CREATE TABLE gocql_test.test_single_routing_key (first_id int, second_id int, PRIMARY KEY (first_id, second_id))"); err != nil {
+	// Use a unique suffix so the test can run in parallel or with -count=N.
+	suffix := fmt.Sprintf("%d", time.Now().UnixNano())
+	singleTable := "test_single_rk_" + suffix
+	compositeTable := "test_composite_rk_" + suffix
```
Comment (dkropachev) [inline cassandra_test.go]: let's just have a function that composes table name of the test name (t.Name()), consider that test name could be longer than 48 chars allowed by CQL, in such case you could have something like this: test_<first_10_chars>_<hash>_<last_10_chars>
We will reuse it for other tests too

**Review by sylwiaszunejko — APPROVED** [review]

File: cassandra_test.go (hunk 2 above)
Comment (mykaul) [reply cassandra_test.go]: Fixed.
